// <auto-generated />
namespace TrueLearn.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class test_roles_and_settings : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test_roles_and_settings));
        
        string IMigrationMetadata.Id
        {
            get { return "201908021229397_test_roles_and_settings"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
